### PR TITLE
Fix large quantity bugs

### LINKED ISSUE #211: [PE-D] App does not respond to large integers input
`sale add c/2 n/Guitar Tuner d/2020-10-30 15:50 p/10.00 q/10000000000 t/music`

With the command above, the app does not do anything, perhaps could add a check on quantity that are too large.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: YangJiyu98/ped#7

### PR DESCRIPTION
**Pull request by hakujitsu**
Closes #211 

**Changes Made**
- Add additional validation for Unit Price and Quantity to ensure a max value of 10 million
- Amend existing test cases for Unit Price and Quantity
- Add test cases for parsing Sale related fields in parserUtil
- Refactor parsing methods for Unit Price and Quantity
- Fix documentation to specify the maximum value of Unit Price and Quantity
- Add dollar sign to UnitPrice toString method

Screenshot 2020-11-01 at 4 42 47 AM

Screenshot 2020-11-01 at 4 41 50 AM

### CODE REVIEW

File: src/main/java/seedu/address/model/sale/Quantity.java [hunk 1]
```diff
@@ -10,31 +10,30 @@
 public class Quantity {
 
     public static final String MESSAGE_CONSTRAINTS =
-            "Quantity should be a positive integer, and it should not be blank";
+            "Quantity should be a positive integer less than 10 million, and should not be blank";
```
Comment (Asthenosphere) [inline src/main/java/seedu/address/model/sale/Quantity.java]:
```suggestion
            "Quantity should be a positive integer less than 10 million, and should not be blank.";
```

File: src/test/java/seedu/address/model/sale/UnitPriceTest.java [hunk 2]
```diff
@@ -31,11 +31,17 @@ public void isValidUnitPriceString() {
         assertFalse(UnitPrice.isValidUnitPriceString("^")); // only non-numeric characters
         assertFalse(UnitPrice.isValidUnitPriceString("11")); // without . character
         assertFalse(UnitPrice.isValidUnitPriceString("11.1")); // missing one decimal place
-        assertFalse(UnitPrice.isValidUnitPriceString("11.1")); // missing one decimal place
+        assertFalse(UnitPrice.isValidUnitPriceString("-1.00")); // negative zero
```
Comment (Asthenosphere) [inline src/test/java/seedu/address/model/sale/UnitPriceTest.java]:
```suggestion
        assertFalse(UnitPrice.isValidUnitPriceString("-1.00")); // negative unit price
```

**Review by Asthenosphere — APPROVED** [review]
Tested and works well, good to merge!
