### PR TITLE
Fix duplicate contact issues

### LINKED ISSUE #184: [PE-D] Edit contact allow for duplicate contact
Bug in:
- Contact Feature (Edit contact)

Steps to reproduce:
1- Start from fresh app state (with sample data loaded)
2- Create new contact with different name, phone number, email and remark, without adding contact tag.
3- Edit that newly created contact in step 2 one field by one field to match Alex Yeoh that already exists in the sample data.

Result: A duplicated contact

Not sure if this is the desired outcome, but figured its not since directly adding a duplicate contact is not allowed - "This person already exists in the address book"

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: hansebastian/ped#1

### LINKED ISSUE #198: [PE-D] Unable to add duplicate person
Unable to add a person with the same name but different email address to the app.
OS: Window 10

Steps to reproduce:
1. type in command box `contact add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
2. type in command box `contact add n/John Doe p/98765432 e/joh@example.com a/John street, block 123, #01-01`

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LeeMingDe/ped#2

### PR DESCRIPTION
**Pull request by hakujitsu**
Closes #198, closes #184 

**Changes made**
- Fix contact equality issues: there are now 3 methods checking for equality, hasSameId, isSamePerson, and equals
    - hasSameId is used to identify Persons belonging to Meetings/Remarks/Sales to edit when a Person is updated
    - isSamePerson is used to check for duplicated persons
    - equals (the strictest) verifies that the data and identity fields are identical.
- Clarify criteria for duplicate contact in UG
- Update toString method to only print "Tags" and "Remarks" if any

### CODE REVIEW

File: src/main/java/seedu/address/model/meeting/UniqueMeetingList.java [hunk 1]
```diff
@@ -92,7 +92,7 @@ public void removeMeetingsWithContact(Person contact) {
     public void updateMeetingsWithContact(Person contact) {
         requireNonNull(contact);
         List<Meeting> meetingsToUpdate =
-                internalList.stream().filter(meeting -> meeting.getPersonId() == contact.getId())
+                internalList.stream().filter(meeting -> meeting.getPerson().hasSameId(contact))
```
Comment (sebastiantoh) [inline src/main/java/seedu/address/model/meeting/UniqueMeetingList.java:95]: Just checking, should `UniqueMeetingList#removeMeetingsWithContact` be updated as well? Likewise for `UniqueSaleList` and `UniqueReminderList`

Comment (hakujitsu) [reply src/main/java/seedu/address/model/meeting/UniqueMeetingList.java:95]: Hmm, I feel like it technically isn't needed compared to the updateModelWithContact methods, since removeModelsWithContact should provide the exact contact that matches the one in the model.

Comment (sebastiantoh) [reply src/main/java/seedu/address/model/meeting/UniqueMeetingList.java:95]: I see. Thanks for clarifying! I'll leave Jin Ming to do the approving!

**Review by jmleong666 — APPROVED** [review]
LGTM!
