### PR TITLE
Enhance Sales Functionality

### LINKED ISSUE #102: Wrong Message shown for ListCommand for Sales
The message that explains the ListCommand format for Sales shows the incorrect command format.

### LINKED ISSUE #103: Missing tests for Sales Commands
There are missing tests for the following SalesCommands:
- AddCommand
- ListCommand
- DeleteCommand

### LINKED ISSUE #104: Add Date field to Sales Model
To facilitate analytics for Sales, the date field must be added.

### PR DESCRIPTION
**Pull request by hakujitsu**
Closes #102, closes #103, closes #104 

In this PR, I have done the following:
- Implement Date field for Sales
- Add test for AddCommand, ListCommand and DeleteCommand
- Fix the wrong message shown for ListCommand

In addition, I have also changed the implementation of AddCommand and DeleteCommand. Previously, they added the sale directly to the contact. However, it now creates a deep copy of the person, which is edited and placed into the list. This preserves the immutability of the Person object.

### CODE REVIEW

File: src/main/java/seedu/address/model/sale/Sale.java [hunk 1]
```diff
@@ -90,28 +100,29 @@ public boolean equals(Object other) {
...
+        return Objects.hash(itemName, datetimeOfPurchase, quantity, unitPrice);
     }
 
     @Override
     public String toString() {
         final StringBuilder builder = new StringBuilder();
         builder.append(getItemName())
-                .append(" (Quantity: ")
+                .append(" (Date of Purchase: ")
+                .append(getDatetimeOfPurchase())
```
Comment (jmleong666) [inline src/main/java/seedu/address/model/sale/Sale.java]: Should we format the datetime so that it is consistent with the Meeting `toString()` datetime format?

Comment (hakujitsu) [reply src/main/java/seedu/address/model/sale/Sale.java]: Fixed in latest commit!

**Review by jmleong666 — APPROVED** [review]
LGTM!
